table topic_trends2
	lineageTag: 85f619bf-b8be-41af-b09e-488000065aa4

	column month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 03f2fb2c-ca7e-4063-b851-8848d23ca6dd
		summarizeBy: none
		sourceColumn: month

		variation Variation
			isDefault
			relationship: 95e44cc7-a665-42ca-9829-99187135c637
			defaultHierarchy: LocalDateTable_5aad2c5f-c3ff-4387-8021-4c7602e2be6f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column topic
		dataType: int64
		formatString: 0
		lineageTag: 345364fb-54e1-4d24-95bf-9fdb4abaaf3a
		summarizeBy: none
		sourceColumn: topic

		annotation SummarizationSetBy = Automatic

	column article_count
		dataType: int64
		formatString: 0
		lineageTag: d693eec6-4a9a-42db-b9ce-e9c8597b536c
		summarizeBy: sum
		sourceColumn: article_count

		annotation SummarizationSetBy = Automatic

	partition topic_trends2 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\harsh\OneDrive\Desktop\GradTwin Final Project\topic_trends2.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"month", type date}, {"topic", Int64.Type}, {"article_count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

