table topic_info
	lineageTag: 8de7f004-bc5c-4a4a-8933-103bd0f4638e

	column Topic
		dataType: int64
		formatString: 0
		lineageTag: b215d8e1-715d-4cf7-ae92-6d3ed5304829
		summarizeBy: none
		sourceColumn: Topic

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: int64
		formatString: 0
		lineageTag: 8e3e9dec-3eed-4239-a163-478d1e54dd6e
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 339a0418-9b71-4142-bcbe-7c9a1fdebde9
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Representation
		dataType: string
		lineageTag: 10cceb3d-f080-41c5-9fb4-749ddc2b07dd
		summarizeBy: none
		sourceColumn: Representation

		annotation SummarizationSetBy = Automatic

	column Representative_Docs
		dataType: string
		lineageTag: 66de5c7f-d5be-470e-8c8a-d920c004f684
		summarizeBy: none
		sourceColumn: Representative_Docs

		annotation SummarizationSetBy = Automatic

	partition topic_info = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\harsh\OneDrive\Desktop\GradTwin Final Project\topic_info.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Topic", Int64.Type}, {"Count", Int64.Type}, {"Name", type text}, {"Representation", type text}, {"Representative_Docs", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

